name: task_manager
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.1.2
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
